"""org_id PK fix

Revision ID: e35404209ae5
Revises: 3f643e19bdea
Create Date: 2026-04-29 05:36:16.232675
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e35404209ae5'
down_revision = '3f643e19bdea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('canonical_name', sa.String(length=512), nullable=False),
    sa.Column('entity_kind', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.org_id'], name=op.f('fk_entities_org_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entities'))
    )
    op.create_index(op.f('ix_entities_org_id'), 'entities', ['org_id'], unique=False)
    op.create_table('entity_aliases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('alias', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_entity_aliases_entity_id_entities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity_aliases'))
    )
    op.create_index(op.f('ix_entity_aliases_entity_id'), 'entity_aliases', ['entity_id'], unique=False)
    op.create_table('document_entities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_entities_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_document_entities_entity_id_entities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.org_id'], name=op.f('fk_document_entities_org_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_entities'))
    )
    op.create_index(op.f('ix_document_entities_document_id'), 'document_entities', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_entities_entity_id'), 'document_entities', ['entity_id'], unique=False)
    op.create_index(op.f('ix_document_entities_org_id'), 'document_entities', ['org_id'], unique=False)
    op.alter_column('automation_rules', 'conditions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('automation_rules', 'actions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('automation_runs', 'executed_actions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    
    # Billing indexes
    op.drop_index(op.f('ix_billing_customers_org_id'), table_name='billing_customers')
    op.create_index(op.f('ix_billing_customers_org_id'), 'billing_customers', ['org_id'], unique=True)
    op.drop_index(op.f('ix_billing_customers_stripe_customer_id'), table_name='billing_customers')
    op.create_index(op.f('ix_billing_customers_stripe_customer_id'), 'billing_customers', ['stripe_customer_id'], unique=True)
    op.drop_index(op.f('ix_billing_subscriptions_stripe_subscription_id'), table_name='billing_subscriptions')
    op.create_index(op.f('ix_billing_subscriptions_stripe_subscription_id'), 'billing_subscriptions', ['stripe_subscription_id'], unique=True)
    
    # Document fields
    op.add_column('documents', sa.Column('declared_type', sa.String(length=64), nullable=True))
    op.add_column('documents', sa.Column('confirmed_type', sa.String(length=64), nullable=True))
    op.add_column('documents', sa.Column('type_confidence', sa.Numeric(precision=5, scale=4), nullable=True))
    op.alter_column('documents', 'extracted_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.create_index(op.f('ix_documents_confirmed_type'), 'documents', ['confirmed_type'], unique=False)
    op.create_index(op.f('ix_documents_declared_type'), 'documents', ['declared_type'], unique=False)
    
    # Organizations indexes (avoid dropping unique constraints if possible)
    try:
        op.drop_index(op.f('ix_organizations_org_id'), table_name='organizations')
    except Exception:
        pass
    op.create_index(op.f('ix_organizations_org_id'), 'organizations', ['org_id'], unique=True)
    
    try:
        op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    except Exception:
        pass
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    
    # Processing jobs
    op.drop_index(op.f('ix_processing_jobs_task_id'), table_name='processing_jobs')
    op.create_index(op.f('ix_processing_jobs_task_id'), 'processing_jobs', ['task_id'], unique=True)
    
    # Usage events
    op.alter_column('usage_events', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    
    # Users
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    
    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_org_id_organizations'), 'users', type_='foreignkey')
    op.create_foreign_key(op.f('fk_users_org_id_organizations'), 'users', 'organizations', ['org_id'], ['org_id'])
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('usage_events', 'metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_processing_jobs_task_id'), table_name='processing_jobs')
    op.create_index(op.f('ix_processing_jobs_task_id'), 'processing_jobs', ['task_id'], unique=False)
    op.create_unique_constraint(op.f('uq_processing_jobs_task_id'), 'processing_jobs', ['task_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=False)
    op.drop_index(op.f('ix_organizations_org_id'), table_name='organizations')
    op.create_index(op.f('ix_organizations_org_id'), 'organizations', ['org_id'], unique=False)
    op.create_unique_constraint(op.f('uq_organizations_slug'), 'organizations', ['slug'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_organizations_org_id'), 'organizations', ['org_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(op.f('fk_org_memberships_org_id_organizations'), 'org_memberships', type_='foreignkey')
    op.drop_constraint(op.f('fk_org_memberships_user_id_users'), 'org_memberships', type_='foreignkey')
    op.create_foreign_key(op.f('fk_org_memberships_user_id_users'), 'org_memberships', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('fk_org_memberships_org_id_organizations'), 'org_memberships', 'organizations', ['org_id'], ['org_id'])
    op.drop_index(op.f('ix_documents_declared_type'), table_name='documents')
    op.drop_index(op.f('ix_documents_confirmed_type'), table_name='documents')
    op.alter_column('documents', 'extracted_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('documents', 'type_confidence')
    op.drop_column('documents', 'confirmed_type')
    op.drop_column('documents', 'declared_type')
    op.drop_index(op.f('ix_billing_subscriptions_stripe_subscription_id'), table_name='billing_subscriptions')
    op.create_index(op.f('ix_billing_subscriptions_stripe_subscription_id'), 'billing_subscriptions', ['stripe_subscription_id'], unique=False)
    op.create_unique_constraint(op.f('uq_billing_subscriptions_stripe_subscription_id'), 'billing_subscriptions', ['stripe_subscription_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_billing_customers_stripe_customer_id'), table_name='billing_customers')
    op.create_index(op.f('ix_billing_customers_stripe_customer_id'), 'billing_customers', ['stripe_customer_id'], unique=False)
    op.drop_index(op.f('ix_billing_customers_org_id'), table_name='billing_customers')
    op.create_index(op.f('ix_billing_customers_org_id'), 'billing_customers', ['org_id'], unique=False)
    op.create_unique_constraint(op.f('uq_billing_customers_stripe_customer_id'), 'billing_customers', ['stripe_customer_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_billing_customers_org_id'), 'billing_customers', ['org_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('automation_runs', 'executed_actions',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('automation_rules', 'actions',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('automation_rules', 'conditions',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_index(op.f('ix_document_entities_org_id'), table_name='document_entities')
    op.drop_index(op.f('ix_document_entities_entity_id'), table_name='document_entities')
    op.drop_index(op.f('ix_document_entities_document_id'), table_name='document_entities')
    op.drop_table('document_entities')
    op.drop_index(op.f('ix_entity_aliases_entity_id'), table_name='entity_aliases')
    op.drop_table('entity_aliases')
    op.drop_index(op.f('ix_entities_org_id'), table_name='entities')
    op.drop_table('entities')
    # ### end Alembic commands ###
